# https://docs.spring.io/spring-cloud-stream/reference/rabbit/rabbit_overview/putting-it-all-together.html#page-title
spring:
  cloud:
    stream:
      output-bindings: events # we need explicit bindings bc we use StreamBridge
      bindings:
        events:
          destination: ${A6_EVENTS_RABBITMQ_OUTPUT_EXCHANGE:events} # existing exchange
      rabbit:
        bindings:
          events:
            producer:
              autoBindDlq: false
      binders:
        a6Rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: ${A6_EVENTS_RABBITMQ_HOST:localhost}
                port: ${A6_EVENTS_RABBITMQ_PORT:5672}
                username: ${A6_EVENTS_RABBITMQ_USER:guest}
                password: ${A6_EVENTS_RABBITMQ_PASSWORD:guest}
                virtual-host: ${A6_EVENTS_RABBITMQ_VHOST:/}