context:
  initializer:
    classes: com.angorasix.events.BeansInitializer
server:
  port: ${A6_EVENTS_PORT:9087}

spring:
  config:
    import: classpath:/api.yml, classpath:/security.yml, classpath:/amqp.yml
  application:
    name: ${A6_EVENTS_APP_NAME:events}

logging:
  level:
    org.springframework.cloud.stream: ${A6_EVENTS_LOGGING_LEVEL_INFRA_STREAM:INFO}
